# Site settings
author: Emilia M
title: The Brazil Experience
header-img: img/home-bg.png
email: emilia.mena26@gmail.com
copyright_name: Emilia M
description: > # this means to ignore newlines until "baseurl:"
  CLI Data Gem Portfolio Project - brazil_experience
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  emilia-m26

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
